{% set name = "andes" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55d285346191e326e3f06c9dabdd586e154fdaa91ea82dea2852a893bcd3ef3d

build:
  number: 0
  entry_points:
    - andes = andes.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dill
    - cvxopt >=1.2.3
    - numpy
    - scipy
    - sympy <1.6
    - pandas
    - xlrd
    - xlsxwriter
    - tqdm
    - pyyaml
    - pathos
    - coloredlogs
    - matplotlib-base

test:
  imports:
    - andes
  requires:
    - pytest
  commands:
    - andes

about:
  home: https://github.com/cuihantao/andes
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Python Software for Symbolic Power System Modeling and Numerical Analysis
  doc_url: https://andes.readthedocs.io
  dev_url: https://github.com/cuihantao/andes

extra:
  recipe-maintainers:
    - cuihantao
