{% set name = "andes" %}
{% set version = "0.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 497c647693b54c64f59ecef017f88a28c3111c297294801905ab2f5924e6e316

build:
  number: 0
  entry_points:
    - andes = andes.main:main
    - andesplot = andes.plot:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - cvxopt
    - matplotlib
    - numpy
    - pandas
    - python
    - scipy
    - sympy
    - texttable

test:
  imports:
    - andes
    - andes.config
    - andes.filters
    - andes.formats
    - andes.models
    - andes.routines
    - andes.utils
    - andes.variables
  commands:
    - andes --help
    - andesplot --help

about:
  home: https://github.com/cuihantao/andes
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Another Power System Simulator
  doc_url: https://andes.readthedocs.io 
  dev_url: https://github.com/cuihantao/andes

extra:
  recipe-maintainers:
    - cuihantao
