{% set name = "andes" %}
{% set version = "0.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6550138e26259434ba7f4d1dcca3d2ad80e0d9e18043ea5517e13bbeed441fe3

build:
  number: 1
  entry_points:
    - andes = andes.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dill
    - cvxopt
    - numpy
    - scipy
    - sympy
    - pandas
    - xlrd
    - xlsxwriter
    - tqdm
    - pyyaml
    - coloredlogs
    - matplotlib-base

test:
  imports:
    - andes
  requires:
    - pytest
  commands:
    - andes

about:
  home: https://github.com/cuihantao/andes
  license: GNU Public License v3+
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A hybrid symbolic-numeric power system simulator
  doc_url: https://andes.readthedocs.io 
  dev_url: https://github.com/cuihantao/andes

extra:
  recipe-maintainers:
    - cuihantao
