travis:
  secure:
    BINSTAR_TOKEN: dBooYXTqI4XjTgtT0Biv4tJtfGhHSAUpgR4+KGcL2aeAwz8wXTAqgSji9YwWLPcbqokizbXCvsqXZqDZwuT7kEawl9H5t9voFHyP3Jhz5Xija6hZdLJ8Brk5s2ZuHUkfio2F+Q1J1+BtCNn3g8bVRQ517IwkpGNzxeZ4m4cBwhNGZIy/PByG2EyV050p2shr8HQLe5GzjyunRKZkRFtL1xgVtGmuVS6HwvKwAgF89hz2lW8IGF+5scWV+w+axm7MpUgs/NWUWuDCQYt9dEkK/3Gv8jonhtGiA6aOLKfBC5f7v6TdaRcJk+foylQpHUid87Cd5VeZcq+93gsdBiZEojhJyPlx8Dec8Ro6r7jB1xLWeczbxMSVz74JhvVhEPu2Pwa/ydrBp++1w0UdfNtHoEYUU2znGYJjr8tzmnadDrzCUbw+UEoukBi/fU9FyQ+zzyEgiSOm888aVV0p79rsqQZY6vOeH/nmWa05XfuBzegcfEvcZp2zjMMiZz9QSFPpZC+DtdZjdZu7bhmvivvMdRknKyls52SjvDjU7b1PcN8K/xucpr2Bt7aYjD1htrAY+5fHQ2QI5VOsqu71dlDXC4zspLk1zbRS/pTRWhz7hPlTCZPuMwOTebziQ+Ku9E/YpVc0cCsMihjsqHU+nJ7hWulUo5vASry8jmoBT5r002s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
